// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareRouteur.Data;

#nullable disable

namespace SoftwareRouteur.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518065348_AddScheduleBlockDestination")]
    partial class AddScheduleBlockDestination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SoftwareRouteur.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.BlockedTraffic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DstIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dst_ip");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logged_at");

                    b.Property<string>("SrcIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("src_ip");

                    b.HasKey("Id");

                    b.ToTable("blocked_traffic");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("int")
                        .HasColumnName("child_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("ParentProfileId")
                        .HasColumnType("int")
                        .HasColumnName("parent_profile_id");

                    b.Property<bool>("ProofRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("proof_required");

                    b.Property<int>("RewardMinutes")
                        .HasColumnType("int")
                        .HasColumnName("reward_minutes");

                    b.Property<string>("RewardScope")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reward_scope");

                    b.Property<string>("RewardSite")
                        .HasColumnType("longtext")
                        .HasColumnName("reward_site");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("ParentProfileId");

                    b.ToTable("challenges");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.ChallengeProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proof_type");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_proofs");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("OpnsenseAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_alias_uuid");

                    b.Property<string>("OpnsenseAllowRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_allow_rule_uuid");

                    b.Property<string>("OpnsenseRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_rule_uuid");

                    b.Property<string>("OpnsenseWhitelistUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_whitelist_uuid");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.FirewallRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destination");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_global");

                    b.Property<string>("OpnsenseAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_alias_uuid");

                    b.Property<string>("OpnsenseRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_rule_uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rule_type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("firewall_rules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Monitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveRules")
                        .HasColumnType("int")
                        .HasColumnName("active_rules");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checked_at");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_ip");

                    b.Property<string>("Hostname")
                        .HasColumnType("longtext")
                        .HasColumnName("hostname");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_online");

                    b.HasKey("Id");

                    b.ToTable("monitoring");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("OpnsenseAllowAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_allow_alias_uuid");

                    b.Property<string>("OpnsenseAllowRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_allow_rule_uuid");

                    b.Property<string>("OpnsenseBlockAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_block_alias_uuid");

                    b.Property<string>("OpnsenseBlockRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_block_rule_uuid");

                    b.Property<string>("OpnsenseSrcAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_src_alias_uuid");

                    b.Property<string>("PinHash")
                        .HasColumnType("longtext")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.ProfileFirewallRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destination");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rule_type");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("profile_firewall_rules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int")
                        .HasColumnName("challenge_id");

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("int")
                        .HasColumnName("child_profile_id");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("RemainingSeconds")
                        .HasColumnType("int")
                        .HasColumnName("remaining_seconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int")
                        .HasColumnName("total_minutes");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("ClientId");

                    b.ToTable("rewards");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockDestination")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("block_destination");

                    b.Property<string>("BlockDestinationType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("block_destination_type");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("days");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_blocking");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<TimeOnly>("TimeEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("time_end");

                    b.Property<TimeOnly>("TimeStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("time_start");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfileId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.TempAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProfileId");

                    b.ToTable("temp_authorizations");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Challenge", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftwareRouteur.Models.Profile", "ParentProfile")
                        .WithMany()
                        .HasForeignKey("ParentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("ParentProfile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.ChallengeProof", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Challenge", "Challenge")
                        .WithMany("Proofs")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "Profile")
                        .WithMany("Clients")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.FirewallRule", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Client", "Client")
                        .WithMany("FirewallRules")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.ProfileFirewallRule", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "Profile")
                        .WithMany("ProfileFirewallRules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Reward", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Challenge", "Challenge")
                        .WithOne("Reward")
                        .HasForeignKey("SoftwareRouteur.Models.Reward", "ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftwareRouteur.Models.Profile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftwareRouteur.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Challenge");

                    b.Navigation("ChildProfile");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Schedule", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoftwareRouteur.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.TempAuthorization", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoftwareRouteur.Models.Profile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftwareRouteur.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedBy");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Challenge", b =>
                {
                    b.Navigation("Proofs");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.Navigation("FirewallRules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("ProfileFirewallRules");
                });
#pragma warning restore 612, 618
        }
    }
}
